#!/usr/bin/env python3
"""
Training Script for Depth Anything V2 Pseudo-Label Training.

This script demonstrates how to train a student model (ViT-S or ViT-B) using
pseudo-labels generated by a teacher model (ViT-L).

Usage:
    python train_pseudo_label.py --config <path_to_config>
    
Example:
    python train_pseudo_label.py \
        --image_dir ./data/images \
        --student_model vits \
        --num_epochs 50 \
        --batch_size 8
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional
import logging

import torch

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from da2.config import DA2TrainingConfig
from da2.teacher_model import DepthAnythingV2Teacher
from da2.student_model import StudentModelWrapper
from da2.pseudo_label_dataset import (
    DA2PseudoLabelDataset, 
    create_dataloader,
    precompute_all_pseudo_labels,
)
from da2.train_utils import (
    PseudoLabelLoss,
    validate_student_model,
    WarmupCosineScheduler,
    AverageMeter,
)

# Optional tensorboard import
try:
    from torch.utils.tensorboard import SummaryWriter
    HAS_TENSORBOARD = True
except ImportError:
    HAS_TENSORBOARD = False
    SummaryWriter = None


def setup_logging(log_dir: str) -> logging.Logger:
    """Setup logging configuration."""
    os.makedirs(log_dir, exist_ok=True)
    
    log_file = os.path.join(log_dir, "training.log")
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler()
        ]
    )
    
    return logging.getLogger(__name__)


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Train student model with pseudo-labels from Depth Anything V2 ViT-L")
    
    # Data arguments
    parser.add_argument("--image_dir", type=str, default="./data/images",
                        help="Directory containing training images")
    parser.add_argument("--pseudo_label_dir", type=str, default="./data/pseudo_labels",
                        help="Directory to save/load pseudo-labels")
    parser.add_argument("--precompute", action="store_true", default=True,
                        help="Precompute pseudo-labels before training")
    
    # Model arguments
    parser.add_argument("--teacher_checkpoint", type=str, default=None,
                        help="Path to teacher model checkpoint (ViT-L)")
    parser.add_argument("--student_model", type=str, default="vits", choices=["vits", "vitb", "custom"],
                        help="Student model type")
    parser.add_argument("--student_checkpoint", type=str, default=None,
                        help="Path to student model checkpoint (for fine-tuning)")
    parser.add_argument("--no_pretrained", action="store_true",
                        help="Don't use pretrained weights for student")
    
    # Training arguments
    parser.add_argument("--batch_size", type=int, default=8,
                        help="Batch size for training")
    parser.add_argument("--num_epochs", type=int, default=50,
                        help="Number of training epochs")
    parser.add_argument("--warmup_epochs", type=int, default=5,
                        help="Number of warmup epochs")
    parser.add_argument("--lr", type=float, default=1e-4,
                        help="Learning rate")
    parser.add_argument("--weight_decay", type=float, default=0.01,
                        help="Weight decay")
    parser.add_argument("--loss_type", type=str, default="combined",
                        choices=["mse", "silog", "combined"],
                        help="Loss function type")
    
    # Optimization arguments
    parser.add_argument("--optimizer", type=str, default="adamw",
                        choices=["adamw", "adam", "sgd"],
                        help="Optimizer type")
    parser.add_argument("--scheduler", type=str, default="cosine",
                        choices=["cosine", "step", "linear"],
                        help="Learning rate scheduler")
    parser.add_argument("--gradient_clip", type=float, default=1.0,
                        help="Gradient clipping value")
    
    # Hardware arguments
    parser.add_argument("--device", type=str, default="cuda",
                        help="Device to use (cuda or cpu)")
    parser.add_argument("--mixed_precision", action="store_true", default=True,
                        help="Use mixed precision training")
    
    # Logging and checkpointing
    parser.add_argument("--log_dir", type=str, default="./logs/da2_training",
                        help="Directory for logs")
    parser.add_argument("--checkpoint_dir", type=str, default="./checkpoints/da2_training",
                        help="Directory for checkpoints")
    parser.add_argument("--save_every", type=int, default=5,
                        help="Save checkpoint every N epochs")
    parser.add_argument("--eval_every", type=int, default=1,
                        help="Evaluate every N epochs")
    
    # Other arguments
    parser.add_argument("--output_resolution", type=int, nargs=2, default=[518, 518],
                        help="Output resolution for depth prediction")
    parser.add_argument("--confidence_threshold", type=float, default=0.0,
                        help="Minimum confidence threshold for pseudo-labels")
    
    return parser.parse_args()


def build_optimizer(model: torch.nn.Module, config: DA2TrainingConfig) -> torch.optim.Optimizer:
    """Build optimizer based on configuration."""
    if config.optimizer == "adamw":
        return torch.optim.AdamW(
            model.parameters(),
            lr=config.learning_rate,
            weight_decay=config.weight_decay,
        )
    elif config.optimizer == "adam":
        return torch.optim.Adam(
            model.parameters(),
            lr=config.learning_rate,
            weight_decay=config.weight_decay,
        )
    elif config.optimizer == "sgd":
        return torch.optim.SGD(
            model.parameters(),
            lr=config.learning_rate,
            momentum=0.9,
            weight_decay=config.weight_decay,
        )
    else:
        raise ValueError(f"Unsupported optimizer: {config.optimizer}")


def train_epoch(
    model: StudentModelWrapper,
    dataloader: torch.utils.data.DataLoader,
    criterion: PseudoLabelLoss,
    optimizer: torch.optim.Optimizer,
    scheduler: Optional[WarmupCosineScheduler],
    device: torch.device,
    epoch: int,
    logger: logging.Logger,
    writer: SummaryWriter,
    gradient_clip: float = 1.0,
    mixed_precision: bool = True,
) -> float:
    """Train for one epoch."""
    model.train()
    
    loss_meter = AverageMeter("Loss")
    scaler = torch.cuda.amp.GradScaler() if mixed_precision and device.type == "cuda" else None
    
    for batch_idx, batch in enumerate(dataloader):
        images = batch['images'].to(device)
        depths = batch['depths'].to(device)
        confidences = batch.get('confidences', None)
        if confidences is not None:
            confidences = confidences.to(device)
        
        optimizer.zero_grad()
        
        # Mixed precision forward pass
        if scaler is not None:
            with torch.cuda.amp.autocast():
                predictions = model(images)
                loss = criterion(predictions, depths, confidences)
            
            scaler.scale(loss).backward()
            
            # Gradient clipping
            if gradient_clip > 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), gradient_clip)
            
            scaler.step(optimizer)
            scaler.update()
        else:
            predictions = model(images)
            loss = criterion(predictions, depths, confidences)
            loss.backward()
            
            if gradient_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), gradient_clip)
            
            optimizer.step()
        
        if scheduler is not None:
            scheduler.step()
        
        loss_meter.update(loss.item(), images.size(0))
        
        # Log progress
        if batch_idx % 10 == 0:
            logger.info(f"Epoch [{epoch}] Batch [{batch_idx}/{len(dataloader)}] Loss: {loss_meter.avg:.4f} LR: {scheduler.get_lr() if scheduler else optimizer.param_groups[0]['lr']:.6f}")
    
    # Log to tensorboard
    if writer is not None:
        writer.add_scalar("train/loss", loss_meter.avg, epoch)
        writer.add_scalar("train/lr", optimizer.param_groups[0]['lr'], epoch)
    
    return loss_meter.avg


def main():
    """Main training function."""
    args = parse_args()
    
    # Create configuration
    config = DA2TrainingConfig(
        image_dir=args.image_dir,
        pseudo_label_dir=args.pseudo_label_dir,
        precompute_pseudo_labels=args.precompute,
        teacher_checkpoint_path=args.teacher_checkpoint,
        student_model_type=args.student_model,
        student_checkpoint_path=args.student_checkpoint,
        student_pretrained=not args.no_pretrained,
        batch_size=args.batch_size,
        num_epochs=args.num_epochs,
        warmup_epochs=args.warmup_epochs,
        learning_rate=args.lr,
        weight_decay=args.weight_decay,
        loss_type=args.loss_type,
        optimizer=args.optimizer,
        scheduler=args.scheduler,
        gradient_clip=args.gradient_clip,
        device=args.device,
        mixed_precision=args.mixed_precision,
        output_resolution=tuple(args.output_resolution),
        confidence_threshold=args.confidence_threshold,
        log_dir=args.log_dir,
        checkpoint_dir=args.checkpoint_dir,
        save_every_n_epochs=args.save_every,
        eval_every_n_epochs=args.eval_every,
    )
    
    # Setup logging
    logger = setup_logging(config.log_dir)
    logger.info("Starting Depth Anything V2 Pseudo-Label Training")
    logger.info(f"Configuration: {config}")
    
    # Setup TensorBoard
    writer = None
    if HAS_TENSORBOARD:
        writer = SummaryWriter(log_dir=config.log_dir)
    else:
        logger.warning("TensorBoard not available. Install with: pip install tensorboard")
    
    # Setup device
    device = torch.device(config.device if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")
    
    # Initialize teacher model
    logger.info("Initializing teacher model (ViT-L)...")
    teacher = DepthAnythingV2Teacher(
        checkpoint_path=config.teacher_checkpoint_path,
        device=device,
        output_resolution=config.output_resolution,
        normalize_depth=config.normalize_depth,
    )
    
    # Precompute pseudo-labels if requested
    if config.precompute_pseudo_labels:
        logger.info("Precomputing pseudo-labels...")
        precompute_all_pseudo_labels(
            teacher_model=teacher,
            image_dir=config.image_dir,
            output_dir=config.pseudo_label_dir,
            batch_size=config.batch_size,
        )
    
    # Initialize student model
    logger.info(f"Initializing student model ({config.student_model_type})...")
    student = StudentModelWrapper(
        model_type=config.student_model_type,
        checkpoint_path=config.student_checkpoint_path,
        pretrained=config.student_pretrained,
        device=device,
    )
    
    # Create dataset and dataloader
    logger.info("Creating dataset...")
    train_dataset = DA2PseudoLabelDataset(
        image_dir=config.image_dir,
        pseudo_label_dir=config.pseudo_label_dir,
        precompute=config.precompute_pseudo_labels,
        target_resolution=config.output_resolution,
        normalize_depth=config.normalize_depth,
        confidence_threshold=config.confidence_threshold,
    )
    
    train_loader = create_dataloader(
        train_dataset,
        batch_size=config.batch_size,
        num_workers=config.num_workers,
        shuffle=True,
    )
    
    # Create validation split (optional - use last 10% of data)
    val_size = max(1, len(train_dataset) // 10)
    train_size = len(train_dataset) - val_size
    train_subset, val_subset = torch.utils.data.random_split(
        train_dataset, [train_size, val_size]
    )
    
    val_loader = create_dataloader(
        val_subset,
        batch_size=config.batch_size,
        num_workers=2,
        shuffle=False,
    )
    
    # Build loss function
    criterion = PseudoLabelLoss(
        loss_type=config.loss_type,
        confidence_weighting=config.use_confidence_weighting,
    )
    
    # Build optimizer
    optimizer = build_optimizer(student, config)
    
    # Build scheduler
    scheduler = WarmupCosineScheduler(
        optimizer=optimizer,
        warmup_epochs=config.warmup_epochs,
        total_epochs=config.num_epochs,
        base_lr=config.learning_rate,
        min_lr=1e-6,
    )
    
    # Training loop
    logger.info("Starting training...")
    best_val_loss = float('inf')
    
    for epoch in range(1, config.num_epochs + 1):
        logger.info(f"\n{'='*50}")
        logger.info(f"Epoch {epoch}/{config.num_epochs}")
        logger.info(f"{'='*50}")
        
        # Train
        train_loss = train_epoch(
            model=student,
            dataloader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            scheduler=scheduler,
            device=device,
            epoch=epoch,
            logger=logger,
            writer=writer,
            gradient_clip=config.gradient_clip,
            mixed_precision=config.mixed_precision,
        )
        
        logger.info(f"Train Loss: {train_loss:.4f}")
        
        # Evaluate
        if epoch % config.eval_every_n_epochs == 0:
            logger.info("Evaluating...")
            val_metrics = validate_student_model(
                model=student,
                dataloader=val_loader,
                device=device,
                loss_fn=criterion,
            )
            
            logger.info("Validation Metrics:")
            for key, value in val_metrics.items():
                logger.info(f"  {key}: {value:.4f}")
                if writer is not None:
                    writer.add_scalar(f"val/{key}", value, epoch)
            
            # Save best model
            if val_metrics.get('val_loss', float('inf')) < best_val_loss:
                best_val_loss = val_metrics.get('val_loss', float('inf'))
                best_checkpoint_path = os.path.join(config.checkpoint_dir, "best_model.pth")
                student.save_checkpoint(best_checkpoint_path, epoch, optimizer)
                logger.info(f"Saved best model to {best_checkpoint_path}")
        
        # Save checkpoint
        if epoch % config.save_every_n_epochs == 0:
            checkpoint_path = os.path.join(config.checkpoint_dir, f"checkpoint_epoch_{epoch}.pth")
            student.save_checkpoint(checkpoint_path, epoch, optimizer)
            logger.info(f"Saved checkpoint to {checkpoint_path}")
    
    # Final evaluation
    logger.info("\nFinal Evaluation...")
    final_metrics = validate_student_model(
        model=student,
        dataloader=val_loader,
        device=device,
        loss_fn=criterion,
    )
    
    logger.info("Final Validation Metrics:")
    for key, value in final_metrics.items():
        logger.info(f"  {key}: {value:.4f}")
    
    # Save final model
    final_checkpoint_path = os.path.join(config.checkpoint_dir, "final_model.pth")
    student.save_checkpoint(final_checkpoint_path, config.num_epochs, optimizer)
    logger.info(f"Saved final model to {final_checkpoint_path}")
    
    if writer is not None:
        writer.close()
    logger.info("Training completed!")


if __name__ == "__main__":
    main()
